language: node_js
os: linux
dist: bionic
node_js: node

branches:
  only:
  - master

cache: 
  yarn: true

install: yarn --frozen-lockfile
script: yarn build
deploy:
  provider: pages
  local_dir: dist
  target_branch: gh-pages
  committer_from_gh: true
  skip_cleanup: true
  cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
