language: node_js
os: linux
dist: bionic
node_js: node

cache: 
  yarn: true

before_install:
  - wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - rm packages-microsoft-prod.deb
  - sudo add-apt-repository universe
  - sudo apt-get -q update
  - sudo apt-get -y install apt-transport-https
  - sudo apt-get -q update
  - sudo apt-get -y install dotnet-sdk-3.1

install: yarn --frozen-lockfile
script: 
  - yarn build
deploy:
  - on:
      all_branches: true
    provider: pages
    local_dir: dist
    target_branch: gh-pages
    committer_from_gh: true
    cleanup: false
    skip_cleanup: true
    token: $GITHUB_TOKEN
    fqdn: slo-covid-19-stage.rtfm.si
    verbose: true
    deploy_strategy: git
  - on:
      branch: master
    provider: pages
    local_dir: dist
    repo: slo-covid-19/slo-covid-19.github.io
    target_branch: master
    committer_from_gh: true
    cleanup: false
    skip_cleanup: true
    token: $GITHUB_TOKEN
    fqdn: covid-19.sledilnik.org
    verbose: true
    deploy_strategy: git

notifications:
  slack:
    secure: FheQRNd6784jPKjRbMCKJypjLLnHxovWWtVb6Im9fEzY2e6g9UpSH25q7PqWcN3tCstPUQAA3n1B6kKptu3rO3b4kE7uEi5ADA1M0FIWNtquGqsJNnS/ws4K7R7ejRaBsk4dMg55Y3DfF/WqUnzHjL4VHkKThn/Mmm2Whyfi63AWhnZuYjwqfp2ZcgVMDEwdhSFYd5+Xx4XyGBh/BOmv6voyqoMeYN1sZ8C5h/jvKIpzr2Je50bKWD0HjJYKG8BP2gEyrkxk/PGA9cT+WVJFs3OEQJlj69foXdhdr32Tq0EbcqXXUmoz1zq+FIgDiteOVvQKQKCDeLOtFodjrkB+sCY5v8ZHQPbc+9Pm4C4LRNQ3k3WMPidFf5ZQFSQhB0mjqYcL8seDZBfGK81uA60w/bzseGN8k25klh5vnAQBuVKVDB/QdDcVCrUw9nrw+D381X5+GxujSSVMoO7gbckTmKGeJtClAUBehT4O4MPzSfOMBlwWLJfQVjnl7wceWzPXTsNjZdxn4jeBLo5MmnQqlqpdRW6KHcrorLwSgkDeegWBen4pFv3xnk2WoTXSyzNNGemN6fieMDkfNep5NCT2pPrdJsT5IrX+3VL1g80phgnrPG/YthNx9CjGvQOk8QOo6CG1U+8mWGd0Q4DkwXHi+wp585oPq4W2JcL0dHdyrZ8=
